### ISSUE TITLE
Bug - Character sheets not syncing correctly

### ISSUE THREAD

**Issue by stuttste** [hitcherland/FoundryVTT-Heart#40] opened 2022-06-22 18:20 UTC
This has been something that's popped up since we started running the game, but I was trying to deduce some sort of pattern. I have yet to figure out what causes the behavior.

The issue is when someone in the game updates a character sheet (alters beats/abilities or adds equipment/resources) the sheet sometimes doesn't update for the GM and vice versa.

Typically, for beats and abilities, clicking the eye icon for them seems to refresh them somewhat consistently. It's unclear what updates equipment or resources when this occurs, but they eventually sync back up.

**Comment by Wigginns** [comment] 2023-03-05 16:32
The most consistent fix I've found is to refresh the entire page though that's a pain for sure. 

This is on my "To Investigate" list.

**Comment by hitcherland** [comment] 2023-09-09 10:42
Duplicate of #62 

I'm going to close this while I look into a more recent issue occurence.

**Closed by hitcherland** 2023-09-09 10:42 UTC
